spring:
  application:
    name: fbrl-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fbrl_db
    username: fbrl_user
    password: fbrlpassword
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false

  data:
    redis:
      host: localhost
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:false}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true

  batch:
    job:
      enabled: false

  sql:
    init:
      mode: never
      schema-locations: classpath:db/batch-schema-postgresql.sql

kafka:
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID:transfer-event-processor}
  topic:
    transfer-events: ${KAFKA_TOPIC_TRANSFER_EVENTS:transfer-events}

shedlock:
  environment: ${SHEDLOCK_ENVIRONMENT:fbrl-backend}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

logging:
  level:
    root: WARN
    com.fbrl: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.orm.session: ERROR
    org.springframework: WARN

k8s:
  leader-election:
    enabled: false
    namespace: default
    lease-name: eod-settlement-leader
    lease-duration-seconds: 15
    renew-deadline-seconds: 10
    retry-period-seconds: 2

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000

jwt:
  secret: "local-dev-only-jwt-signing-secret-change-in-production-32bytes-min"
  expiration-seconds: 3600

approval:
  threshold: 10000000

fraud:
  threshold: 50000000

eod:
  batch:
    cron: "0 0 2 * * *"

reconciliation:
  batch:
    cron: "0 0 3 * * *"

demo:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/fbrl_demo_db
    username: fbrl_user
    password: fbrlpassword
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  eod:
    batch:
      cron: "0 10 2 * * *"
  reconciliation:
    batch:
      cron: "0 20 3 * * *"